<?php
/**
 * @file
 * hk_translations.features.translations.inc
 */

/**
 * Implements hook_translations_defaults().
 */
function hk_translations_translations_defaults() {
  $translations = array();
  $translations['de:blocks']['32c83e92288e32d2dd9f719cca82bdf1'] = array(
    'source' => 'Rooms',
    'context' => 'facetapi:kGwOvwemd6S00xeaSwCCPvDt2xe1AhtY:title',
    'location' => 'blocks:facetapi:kGwOvwemd6S00xeaSwCCPvDt2xe1AhtY:title',
    'translation' => 'Zimmer',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:blocks']['37438b333567f577a56e1d827b45ae2a'] = array(
    'source' => 'Borough',
    'context' => 'facetapi:jad3t4v2COeMFwB0yX94d90ie3s200aH:title',
    'location' => 'blocks:facetapi:jad3t4v2COeMFwB0yX94d90ie3s200aH:title',
    'translation' => 'Bezirk',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:blocks']['572851a7a2bf45244a3b54ba23217352'] = array(
    'source' => 'Price',
    'context' => 'facetapi:vih09cZclFZTB71YMojA1b30XzODYv0m:title',
    'location' => 'blocks:facetapi:vih09cZclFZTB71YMojA1b30XzODYv0m:title',
    'translation' => 'Preis',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:blocks']['5f9958335c577f150a3ff06a1c96103f'] = array(
    'source' => 'Category',
    'context' => 'facetapi:v9PrDdEwtlkfDhtYYCNF11LEvdlX2kmo:title',
    'location' => 'blocks:facetapi:v9PrDdEwtlkfDhtYYCNF11LEvdlX2kmo:title',
    'translation' => 'Kategorie',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:blocks']['8745aaa348778c799af186177e953ce8'] = array(
    'source' => 'Borough',
    'context' => 'facetapi:qJgpFdYW8mkOWAmYjhDkwkapAV7o0hi5:title',
    'location' => 'blocks:facetapi:qJgpFdYW8mkOWAmYjhDkwkapAV7o0hi5:title',
    'translation' => 'Bezirk',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:blocks']['9971fa8b0770c4f9665ceb1a72b83c59'] = array(
    'source' => 'Space',
    'context' => 'facetapi:MD9nwU0ckZx4U9x9Yq6LhiMOWw1yG2fZ:title',
    'location' => 'blocks:facetapi:MD9nwU0ckZx4U9x9Yq6LhiMOWw1yG2fZ:title',
    'translation' => 'Fläche',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:blocks']['c077312c5c602b0ce8bb87fdd0623e35'] = array(
    'source' => 'Category',
    'context' => 'facetapi:TiTk5IgH07zFSr6CyqVB835ryHANLc1G:title',
    'location' => 'blocks:facetapi:TiTk5IgH07zFSr6CyqVB835ryHANLc1G:title',
    'translation' => 'Kategorie',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:blocks']['ccc1d122f24fe76d0e7a6113ee27595f'] = array(
    'source' => 'Rooms',
    'context' => 'facetapi:UAJ4jVUjkE0k0DL7i0hL8AAiIPUWtpTH:title',
    'location' => 'blocks:facetapi:UAJ4jVUjkE0k0DL7i0hL8AAiIPUWtpTH:title',
    'translation' => 'Zimmer',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:blocks']['e076bbbcdbfa25a661156cc181abc80d'] = array(
    'source' => 'Price',
    'context' => 'facetapi:qlota8bqskQQDsT0ekClqq88wVM1hfnt:title',
    'location' => 'blocks:facetapi:qlota8bqskQQDsT0ekClqq88wVM1hfnt:title',
    'translation' => 'Preis',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:blocks']['e982413f0e7a6aecbb25197df10fd90f'] = array(
    'source' => 'Borough',
    'context' => 'facetapi:iWlNtb8sPj55M5GCIvQfcM0WNi4vPvLS:title',
    'location' => 'blocks:facetapi:iWlNtb8sPj55M5GCIvQfcM0WNi4vPvLS:title',
    'translation' => 'Bezirk',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:blocks']['f58b06c6d6ede38cf84245b5408eafc1'] = array(
    'source' => 'Space',
    'context' => 'facetapi:GJM8LVtVVP0XZXJO510ZLzSDhQG9bCEf:title',
    'location' => 'blocks:facetapi:GJM8LVtVVP0XZXJO510ZLzSDhQG9bCEf:title',
    'translation' => 'Fläche',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:current_search']['1431ba0670817900b1d252c88ac3258e'] = array(
    'source' => '[facetapi_results:result-count] offer',
    'context' => 'suchseiten:results:text',
    'location' => 'current_search:suchseiten:results:text',
    'translation' => '[facetapi_results:result-count] Angebot',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:current_search']['2ee5ab05e3a269c744d11b9046440d5d'] = array(
    'source' => 'Search found [facetapi_results:result-count] items',
    'context' => 'standard:results:text_plural',
    'location' => 'current_search:standard:results:text_plural',
    'translation' => '[facetapi_results:result-count] Angebote gefunden',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:current_search']['473aa19073e1aee05da69e163ae28b64'] = array(
    'source' => 'Search found [facetapi_results:result-count] item',
    'context' => 'standard:results:text',
    'location' => 'current_search:standard:results:text',
    'translation' => '[facetapi_results:result-count] Angebot gefunden',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:current_search']['4bdc74562e036a1dab0781e31bf3fe00'] = array(
    'source' => '[facetapi_results:result-count] offers',
    'context' => 'suchseiten:results:text_plural',
    'location' => 'current_search:suchseiten:results:text_plural',
    'translation' => '[facetapi_results:result-count] Angebote',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:facetapi']['270e3da1c9416d0df7f4183db623e511'] = array(
    'source' => '<p>no results</p>',
    'context' => 'search_api_solr_node_index_block_field_object_ref_field_bezirk:empty_text:empty_text',
    'location' => 'facetapi:search_api_solr_node_index_block_field_object_ref_field_bezirk:empty_text:empty_text',
    'translation' => '<p>kein Ergebnis</p> ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:facetapi']['3e4b7406ec2e151ce1c56d70f011e2ca'] = array(
    'source' => '<p>no result</p>',
    'context' => 'search_api_solr_node_index_block_field_object_ref_field_kategorie:empty_text:empty_text',
    'location' => 'facetapi:search_api_solr_node_index_block_field_object_ref_field_kategorie:empty_text:empty_text',
    'translation' => '<p>kein Ergebnis</p> ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['0ade6a3b212df40aad56e4fd85b82d13'] = array(
    'source' => 'The <em>Main</em> menu is used on many sites to show the major sections of the site, often in a top navigation bar.',
    'context' => 'menu:main-menu:description',
    'location' => 'menu:menu:main-menu:description',
    'translation' => 'Das Menu oben neben dem Logo',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['138271edd6c313cb2cab8f89afe36d4a'] = array(
    'source' => 'Rent',
    'context' => 'item:658:title',
    'location' => 'menu:item:658:title',
    'translation' => 'Mieten',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['198b555863941ba6442a4bcd4ee956b2'] = array(
    'source' => 'Wohnungen',
    'context' => 'item:1358:title',
    'location' => 'menu:item:1358:title',
    'translation' => 'Wohnungen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['3742223052d04aeae038ced2178a559a'] = array(
    'source' => 'About us',
    'context' => 'item:799:title',
    'location' => 'menu:item:799:title',
    'translation' => 'Über uns',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['3d3008cee159042ae77ee747fc865e94'] = array(
    'source' => 'Commercial property for sale',
    'context' => 'item:1403:title',
    'location' => 'menu:item:1403:title',
    'translation' => 'Gewerbe Kauf',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['40e62beb0f69c14d4347fdad9204643b'] = array(
    'source' => 'Buy',
    'context' => 'item:1400:title',
    'location' => 'menu:item:1400:title',
    'translation' => 'Kaufen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['47853aa122049d2d6d5d8f2592786352'] = array(
    'source' => 'Capital investment',
    'context' => 'item:1402:title',
    'location' => 'menu:item:1402:title',
    'translation' => 'Vermietete Wohnungen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['518c324da67b662f6f016a3cdafc6b5f'] = array(
    'source' => 'Objekte',
    'context' => 'item:1357:title',
    'location' => 'menu:item:1357:title',
    'translation' => 'Objekte',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['58b58a5fda134f98d7a7616ba09f80f4'] = array(
    'source' => 'Jobs',
    'context' => 'item:1422:title',
    'location' => 'menu:item:1422:title',
    'translation' => 'Jobs',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['5b7ef0e92c5bb31e7389ba217159d81a'] = array(
    'source' => 'Imprint',
    'context' => 'item:782:title',
    'location' => 'menu:item:782:title',
    'translation' => 'Impressum',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['5cf36afb9ce6ecdf2895b7b364262da2'] = array(
    'source' => 'Main menu',
    'context' => 'menu:main-menu:title',
    'location' => 'menu:menu:main-menu:title',
    'translation' => 'Hauptmenu',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['7b074bf42e16a3a448832dd8d21b6ca1'] = array(
    'source' => 'Offer',
    'context' => 'item:798:title',
    'location' => 'menu:item:798:title',
    'translation' => 'Anbieten',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['7b20ba187f992c91a6375d6e4799c411'] = array(
    'source' => 'Terms of Service',
    'context' => 'item:785:title',
    'location' => 'menu:item:785:title',
    'translation' => 'AGB',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['90baa10cc48875f6993bccfc4fbff696'] = array(
    'source' => 'Team',
    'context' => 'item:800:title',
    'location' => 'menu:item:800:title',
    'translation' => 'Team',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['a382479f1a0a8be4eff78a0bda4fa54e'] = array(
    'source' => 'Search',
    'context' => 'item:797:title',
    'location' => 'menu:item:797:title',
    'translation' => 'Suche',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['a67ea8d2f1801e88c5b39e515ea82f2a'] = array(
    'source' => 'Call us',
    'context' => 'item:796:title',
    'location' => 'menu:item:796:title',
    'translation' => 'Rufen Sie uns an',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['adb053502ce650cafde993848167e15a'] = array(
    'source' => 'Favorites',
    'context' => 'item:795:title',
    'location' => 'menu:item:795:title',
    'translation' => 'Favoriten',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['b26d82b733fef86ab3317f9871fb7de0'] = array(
    'source' => 'Privacy Policy',
    'context' => 'item:784:title',
    'location' => 'menu:item:784:title',
    'translation' => 'Datenschutz',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['c851f1b7dd4d084d7c0b5ccc8a9399f3'] = array(
    'source' => 'Contact',
    'context' => 'item:783:title',
    'location' => 'menu:item:783:title',
    'translation' => 'Kontakt',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['e40149f9a29143b40b8fe0a58794e467'] = array(
    'source' => 'Imprint',
    'context' => 'item:802:title',
    'location' => 'menu:item:802:title',
    'translation' => 'Impressum',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['f9267579974d20bbf24d49d4726f3771'] = array(
    'source' => 'Contact',
    'context' => 'item:801:title',
    'location' => 'menu:item:801:title',
    'translation' => 'Kontakt',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['0302ae537c860c0a29d19c25af945d68'] = array(
    'source' => 'Delete',
    'context' => 'crm_core_contacts:default:field:views:nothing_2:alter:text',
    'location' => 'views:crm_core_contacts:default:field:views:nothing_2:alter:text',
    'translation' => 'Löschen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['1d697615d2604879d792720a1f813df0'] = array(
    'source' => 'Address',
    'context' => 'order_locations:default:field:ip_geoloc:formatted_address:label',
    'location' => 'views:order_locations:default:field:ip_geoloc:formatted_address:label',
    'translation' => 'Adresse',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['20ae9c57087f02daadd046b6d007c633'] = array(
    'source' => 'Zimmer',
    'context' => 'karten:kaufen:field:search_api_index_solr_node_index:field_apart_rooms:label',
    'location' => 'views:karten:kaufen:field:search_api_index_solr_node_index:field_apart_rooms:label',
    'translation' => 'Zimmer',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['2ddfd227a593a8f4bf6d888b414a47b4'] = array(
    'source' => 'next ›',
    'context' => 'karten:mieten:pager:tags:next',
    'location' => 'views:karten:mieten:pager:tags:next',
    'translation' => 'vor › ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['2f7db315f05e4f976a0e0cf9145d5b25'] = array(
    'source' => 'Notes',
    'context' => 'crm_anfragen:default:field:field_data_field_activity_notes:field_activity_notes:label',
    'location' => 'views:crm_anfragen:default:field:field_data_field_activity_notes:field_activity_notes:label',
    'translation' => 'Bemerkungen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['33c1de7de1a4e637f219d94964a9a7d9'] = array(
    'source' => 'last »',
    'context' => 'karten:mieten:pager:tags:last',
    'location' => 'views:karten:mieten:pager:tags:last',
    'translation' => 'letzte » ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['3b897e372c065266e9859613cb887655'] = array(
    'source' => '‹ previous',
    'context' => 'karten:kaufen:pager:tags:previous',
    'location' => 'views:karten:kaufen:pager:tags:previous',
    'translation' => '‹ zurück',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['3ddb083c2c2285303879adbe9432cef5'] = array(
    'source' => 'Bezugsfrei ab',
    'context' => 'apartment:details:field:field_data_field_moving_in_from:field_moving_in_from:label',
    'location' => 'views:apartment:details:field:field_data_field_moving_in_from:field_moving_in_from:label',
    'translation' => 'Bezugsfrei ab',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['41baed5b68601562068496c154db1585'] = array(
    'source' => 'Kategorie',
    'context' => 'admin:default:filter:field_data_field_kategorie:field_kategorie_tid:expose:label',
    'location' => 'views:admin:default:filter:field_data_field_kategorie:field_kategorie_tid:expose:label',
    'translation' => 'Kategorie',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['4c9fa2c4fd1c4ac68033c63aef9e8c7b'] = array(
    'source' => 'Edit',
    'context' => 'crm_core_contacts:default:field:views:nothing_1:alter:text',
    'location' => 'views:crm_core_contacts:default:field:views:nothing_1:alter:text',
    'translation' => 'Bearbeiten',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['4d8ff87be5631aab737ba2fdb855a3ca'] = array(
    'source' => 'Rooms',
    'context' => 'karten:kaufen:filter:search_api_index_solr_node_index:field_apart_rooms:expose:label',
    'location' => 'views:karten:kaufen:filter:search_api_index_solr_node_index:field_apart_rooms:expose:label',
    'translation' => 'Zimmer',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['53fde074261a410a6f50e77f51e4d021'] = array(
    'source' => 'Sleeping rooms',
    'context' => 'apartment:details:field:field_data_field_apart_sleeping_rooms:field_apart_sleeping_rooms:label',
    'location' => 'views:apartment:details:field:field_data_field_apart_sleeping_rooms:field_apart_sleeping_rooms:label',
    'translation' => 'Schlafzimmer',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['55784669931ffc53afab0a63e9bbdeaa'] = array(
    'source' => 'next ›',
    'context' => 'karten:kaufen:pager:tags:next',
    'location' => 'views:karten:kaufen:pager:tags:next',
    'translation' => 'vor › ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['55da8299d024c9d9a0cf9cbcbb454fd1'] = array(
    'source' => 'Category',
    'context' => 'admin:wohnungen:field:field_data_field_kategorie:field_kategorie_editable:label',
    'location' => 'views:admin:wohnungen:field:field_data_field_kategorie:field_kategorie_editable:label',
    'translation' => 'Kategorie',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['5861fee556d6f557fbf04e2dfb1f4c09'] = array(
    'source' => 'Search',
    'context' => 'karten:kaufen:exposed_form:submit_button',
    'location' => 'views:karten:kaufen:exposed_form:submit_button',
    'translation' => 'Suche',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['671f3b20e05a581f9611ad1848eb3bcf'] = array(
    'source' => 'Living space',
    'context' => 'karten:kaufen:filter:search_api_index_solr_node_index:field_apart_living_space:expose:label',
    'location' => 'views:karten:kaufen:filter:search_api_index_solr_node_index:field_apart_living_space:expose:label',
    'translation' => 'Fläche',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['7cbd65fe49c0b766951e6fa791e484f7'] = array(
    'source' => 'Fläche',
    'context' => 'karten:kaufen:field:search_api_index_solr_node_index:field_apart_living_space:label',
    'location' => 'views:karten:kaufen:field:search_api_index_solr_node_index:field_apart_living_space:label',
    'translation' => 'Fläche',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['81a7db8af7a816fdaccbeecb285e7c0f'] = array(
    'source' => 'Living space',
    'context' => 'karten:mieten:filter:search_api_index_solr_node_index:field_apart_living_space:expose:label',
    'location' => 'views:karten:mieten:filter:search_api_index_solr_node_index:field_apart_living_space:expose:label',
    'translation' => 'Fläche',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['96a63481b20fdb10413715c2123d4895'] = array(
    'source' => 'Delete',
    'context' => 'admin_views_user:default:action::views_bulk_operations_delete_item',
    'location' => 'views:admin_views_user:default:action::views_bulk_operations_delete_item',
    'translation' => 'Löschen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['9712f2d12d07c75847e9814f7565cb9d'] = array(
    'source' => 'No. of floors',
    'context' => 'apartment:details:field:field_data_field_no_of_floors:field_no_of_floors:label',
    'location' => 'views:apartment:details:field:field_data_field_no_of_floors:field_no_of_floors:label',
    'translation' => 'Etagenzahl',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['9ae34ae6f7d37fc0d9dd04455da5e2dc'] = array(
    'source' => 'Phone',
    'context' => 'crm_dashboard:default:field:field_data_field_phone:field_phone:label',
    'location' => 'views:crm_dashboard:default:field:field_data_field_phone:field_phone:label',
    'translation' => 'Telefon',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['a6329b57c96221bce0d5a5a4a2820db2'] = array(
    'source' => '‹ previous',
    'context' => 'karten:mieten:pager:tags:previous',
    'location' => 'views:karten:mieten:pager:tags:previous',
    'translation' => '‹ zurück',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['a841f2b3119ca5a5ec2a2a76548ec236'] = array(
    'source' => 'Rent',
    'context' => 'karten:mieten:title',
    'location' => 'views:karten:mieten:title',
    'translation' => 'Mieten',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['a8e17808efcea33e70b5bf19118a007d'] = array(
    'source' => '« first',
    'context' => 'karten:mieten:pager:tags:first',
    'location' => 'views:karten:mieten:pager:tags:first',
    'translation' => '« erste',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['b1b47bef5e8ee9f3f965800ccca7299f'] = array(
    'source' => 'Heating type',
    'context' => 'apartment:details:field:field_data_field_heating_type:field_heating_type:label',
    'location' => 'views:apartment:details:field:field_data_field_heating_type:field_heating_type:label',
    'translation' => 'Heizung',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['b1dcb7a68fd55907c880a2a4a05c6c03'] = array(
    'source' => '<a href="/node/[field_obj_apartments-target_id]?destination=admin/content/dash" title="Wohnung ansehen">[field_obj_apartments]</a> | <a href="/node/[field_obj_apartments-target_id]/edit?destination=admin/content/dash" title="Wohnung bearbeiten">bearbeiten</a> | <a href="/node/[field_obj_apartments-target_id]/translate?destination=admin/content/dash" title="Wohnung übersetzen">übersetzen</a>',
    'context' => 'admin:default:field:field_data_field_obj_apartments:field_obj_apartments:alter:text',
    'location' => 'views:admin:default:field:field_data_field_obj_apartments:field_obj_apartments:alter:text',
    'translation' => 'Bearbeiten',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['b6681c7b2f0dadb54e5dc4cd660cf6c0'] = array(
    'source' => 'Rooms',
    'context' => 'karten:mieten:filter:search_api_index_solr_node_index:field_apart_rooms:expose:label',
    'location' => 'views:karten:mieten:filter:search_api_index_solr_node_index:field_apart_rooms:expose:label',
    'translation' => 'Zimmer',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['bb5158b08e24163810fe96ec728d6479'] = array(
    'source' => 'Address',
    'context' => 'visitor_log_lite:default:field:ip_geoloc:formatted_address:label',
    'location' => 'views:visitor_log_lite:default:field:ip_geoloc:formatted_address:label',
    'translation' => 'Adresse',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['beb71bdcade68e169df01e0673af7315'] = array(
    'source' => 'Fläche',
    'context' => 'karten:page_1:field:search_api_index_solr_node_index:field_apart_living_space:label',
    'location' => 'views:karten:page_1:field:search_api_index_solr_node_index:field_apart_living_space:label',
    'translation' => 'Fläche',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['c19b54e0d337ce8764ab835044f34adf'] = array(
    'source' => 'Year built',
    'context' => 'apartment:details:field:field_data_field_year_built:field_year_built:label',
    'location' => 'views:apartment:details:field:field_data_field_year_built:field_year_built:label',
    'translation' => 'Baujahr',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['c361e9a6fc6112e5e54223361d46da51'] = array(
    'source' => 'Purchasing price',
    'context' => 'karten:kaufen:field:search_api_index_solr_node_index:field_apart_price:label',
    'location' => 'views:karten:kaufen:field:search_api_index_solr_node_index:field_apart_price:label',
    'translation' => 'Kaufpreis',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['c486a391ffd9ea6fc701f14b5495b3ca'] = array(
    'source' => 'Floor',
    'context' => 'apartment:details:field:field_data_field_apart_floor:field_apart_floor:label',
    'location' => 'views:apartment:details:field:field_data_field_apart_floor:field_apart_floor:label',
    'translation' => 'Etage',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['c63259125ead603b85bb738e1b20c737'] = array(
    'source' => 'Purchasing price',
    'context' => 'karten:kaufen:filter:search_api_index_solr_node_index:field_apart_price:expose:label',
    'location' => 'views:karten:kaufen:filter:search_api_index_solr_node_index:field_apart_price:expose:label',
    'translation' => 'Kaufpreis',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['ca3c4af2195e8e9b5e1d8d38b22c04ce'] = array(
    'source' => '« first',
    'context' => 'karten:kaufen:pager:tags:first',
    'location' => 'views:karten:kaufen:pager:tags:first',
    'translation' => '« erste',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['caf8b19a455e837abcff880c70ec2ccb'] = array(
    'source' => 'Delete',
    'context' => 'admin_views_file:default:action::views_bulk_operations_delete_item',
    'location' => 'views:admin_views_file:default:action::views_bulk_operations_delete_item',
    'translation' => 'Löschen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['cc6f1bb0212e87002e87a1875ed5b93c'] = array(
    'source' => 'Living space',
    'context' => 'solr_map_apartments:default:field:search_api_index_solr_apartment_index:field_apart_living_space:label',
    'location' => 'views:solr_map_apartments:default:field:search_api_index_solr_apartment_index:field_apart_living_space:label',
    'translation' => 'Fläche',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['d0b89f4175d9703dd8e833952cd88baf'] = array(
    'source' => 'Rooms',
    'context' => 'solr_map_apartments:default:field:search_api_index_solr_apartment_index:field_apart_rooms:label',
    'location' => 'views:solr_map_apartments:default:field:search_api_index_solr_apartment_index:field_apart_rooms:label',
    'translation' => 'Zimmer',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['d6a1f72745f5ccc2fd22e58b0dfaa655'] = array(
    'source' => 'Purchasing price',
    'context' => 'karten:mieten:filter:search_api_index_solr_node_index:field_apart_price:expose:label',
    'location' => 'views:karten:mieten:filter:search_api_index_solr_node_index:field_apart_price:expose:label',
    'translation' => 'Kaufpreis',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['de85bd526fbff261be5afa92bf23cb83'] = array(
    'source' => 'Bathrooms',
    'context' => 'apartment:details:field:field_data_field_apart_bathrooms:field_apart_bathrooms:label',
    'location' => 'views:apartment:details:field:field_data_field_apart_bathrooms:field_apart_bathrooms:label',
    'translation' => 'Badezimmer',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['e14332fa720c41c9b203ceb1d109da3e'] = array(
    'source' => 'Living space',
    'context' => 'karten:default:field:search_api_index_solr_node_index:field_apart_living_space:label',
    'location' => 'views:karten:default:field:search_api_index_solr_node_index:field_apart_living_space:label',
    'translation' => 'Fläche',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['e2ffe0a362859646330e15c196cb1bc6'] = array(
    'source' => 'Status quo',
    'context' => 'apartment:details:field:field_data_field_status_quo:field_status_quo:label',
    'location' => 'views:apartment:details:field:field_data_field_status_quo:field_status_quo:label',
    'translation' => 'Zustand',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['e91836123d301c60c84f398aaffdaa5a'] = array(
    'source' => 'last »',
    'context' => 'backlinks:page:pager:tags:last',
    'location' => 'views:backlinks:page:pager:tags:last',
    'translation' => 'letzte » ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['ea15c337098905a30b438ec836207a57'] = array(
    'source' => 'Address',
    'context' => 'visitor_log:default:field:ip_geoloc:formatted_address:label',
    'location' => 'views:visitor_log:default:field:ip_geoloc:formatted_address:label',
    'translation' => 'Adresse',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['f09139755b9bf76bd015f53f266c1003'] = array(
    'source' => 'Buy',
    'context' => 'karten:kaufen:title',
    'location' => 'views:karten:kaufen:title',
    'translation' => 'Kaufen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['f464c4e214d7d5528d6731337bdb52f2'] = array(
    'source' => 'HOA fee',
    'context' => 'apartment:details:field:field_data_field_apart_hoa_fee:field_apart_hoa_fee:label',
    'location' => 'views:apartment:details:field:field_data_field_apart_hoa_fee:field_apart_hoa_fee:label',
    'translation' => 'Hausgeld',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['f4de2155b1b1d79d3e4dc4879642ed36'] = array(
    'source' => 'last »',
    'context' => 'karten:kaufen:pager:tags:last',
    'location' => 'views:karten:kaufen:pager:tags:last',
    'translation' => 'letzte » ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['f5456069167a5e8a580c21748c91049f'] = array(
    'source' => 'Moving in from',
    'context' => 'apartment:details:field:field_data_field_moving_in_from:field_moving_in_from_1:label',
    'location' => 'views:apartment:details:field:field_data_field_moving_in_from:field_moving_in_from_1:label',
    'translation' => 'Bezugsfrei ab',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['f875fff0bd7d67dc2469b11e208e3587'] = array(
    'source' => 'Rooms',
    'context' => 'karten:mlt:field:search_api_index_solr_node_index:field_zimmer:label',
    'location' => 'views:karten:mlt:field:search_api_index_solr_node_index:field_zimmer:label',
    'translation' => 'Zimmer',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['f8ba9e5f8d885d52dad4aa03336e189e'] = array(
    'source' => 'Delete',
    'context' => 'admin_views_node:default:action::views_bulk_operations_delete_item',
    'location' => 'views:admin_views_node:default:action::views_bulk_operations_delete_item',
    'translation' => 'Löschen',
    'plid' => 0,
    'plural' => 0,
  );
  return $translations;
}
