<?php
/**
 * @file
 * hk_translations.features.translations.inc
 */

/**
 * Implements hook_translations_defaults().
 */
function hk_translations_translations_defaults() {
  $translations = array();
  $translations['de:blocks']['572851a7a2bf45244a3b54ba23217352'] = array(
    'source' => 'Price',
    'context' => 'facetapi:vih09cZclFZTB71YMojA1b30XzODYv0m:title',
    'location' => 'blocks:facetapi:vih09cZclFZTB71YMojA1b30XzODYv0m:title',
    'translation' => 'Preis',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:blocks']['9971fa8b0770c4f9665ceb1a72b83c59'] = array(
    'source' => 'Space',
    'context' => 'facetapi:MD9nwU0ckZx4U9x9Yq6LhiMOWw1yG2fZ:title',
    'location' => 'blocks:facetapi:MD9nwU0ckZx4U9x9Yq6LhiMOWw1yG2fZ:title',
    'translation' => 'Fläche',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:blocks']['c077312c5c602b0ce8bb87fdd0623e35'] = array(
    'source' => 'Category',
    'context' => 'facetapi:TiTk5IgH07zFSr6CyqVB835ryHANLc1G:title',
    'location' => 'blocks:facetapi:TiTk5IgH07zFSr6CyqVB835ryHANLc1G:title',
    'translation' => 'Kategorie',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:blocks']['ccc1d122f24fe76d0e7a6113ee27595f'] = array(
    'source' => 'Rooms',
    'context' => 'facetapi:UAJ4jVUjkE0k0DL7i0hL8AAiIPUWtpTH:title',
    'location' => 'blocks:facetapi:UAJ4jVUjkE0k0DL7i0hL8AAiIPUWtpTH:title',
    'translation' => 'Zimmer',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:blocks']['e982413f0e7a6aecbb25197df10fd90f'] = array(
    'source' => 'Borough',
    'context' => 'facetapi:iWlNtb8sPj55M5GCIvQfcM0WNi4vPvLS:title',
    'location' => 'blocks:facetapi:iWlNtb8sPj55M5GCIvQfcM0WNi4vPvLS:title',
    'translation' => 'Bezirk',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:current_search']['0c9a1acbeda496cbed45e6cb72041c3b'] = array(
    'source' => 'Reset',
    'context' => 'suchseiten:reset:text',
    'location' => 'current_search:suchseiten:reset:text',
    'translation' => 'Zurücksetzen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:current_search']['10dd35c5904750fbe057986743099448'] = array(
    'source' => '[facetapi_facet:facet-label]: ',
    'context' => 'suchseiten:active_filter:field_pattern',
    'location' => 'current_search:suchseiten:active_filter:field_pattern',
    'translation' => '[facetapi_facet:facet-label]: ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['02e413d6c79fccd49063e5ee2803e6ac'] = array(
    'source' => 'Description',
    'context' => 'field_object_description:objekt:label',
    'location' => 'field:field_object_description:objekt:label',
    'translation' => 'Beschreibung',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['05b7df2c1746c2a5664791c5e9e00359'] = array(
    'source' => 'Description Investment',
    'context' => 'field_object_description_invest:objekt:label',
    'location' => 'field:field_object_description_invest:objekt:label',
    'translation' => 'Beschreibung Vermietete Wohnungen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['128f9059fa6ce2244561a4a44f8b788d'] = array(
    'source' => 'Occupancy',
    'context' => 'field_wug_occupancy:residential_commercial_building:label',
    'location' => 'field:field_wug_occupancy:residential_commercial_building:label',
    'translation' => 'Vermietungsstand',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['1429a45143f11d9fd6d820733784043b'] = array(
    'source' => 'Description',
    'context' => 'description_field:heating_type:label',
    'location' => 'field:description_field:heating_type:label',
    'translation' => 'Beschreibung',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['165799511da807daf4f0d8d8abdfdadc'] = array(
    'source' => 'Rooms',
    'context' => 'field_apart_rooms:apartment:label',
    'location' => 'field:field_apart_rooms:apartment:label',
    'translation' => 'Zimmer',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['174c7822544f5878739b283f07f4f616'] = array(
    'source' => 'Central heating',
    'context' => 'field_heating_type:#allowed_values:Central heating',
    'location' => 'field:field_heating_type:#allowed_values:Central heating',
    'translation' => 'Zentralheizung',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['1ef342c5a16352df31f7a0458730eeb6'] = array(
    'source' => 'Renovated',
    'context' => 'field_status_quo:#allowed_values:Renovated',
    'location' => 'field:field_status_quo:#allowed_values:Renovated',
    'translation' => 'Renoviert',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['24b9b571a9495969f4df8add000d2e53'] = array(
    'source' => 'No. of units',
    'context' => 'field_wug_no_of_units:objekt:label',
    'location' => 'field:field_wug_no_of_units:objekt:label',
    'translation' => 'Anzahl Wohneinheiten',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['370b84274677c0d6bc373a920d117dd5'] = array(
    'source' => 'Self-contained central heating',
    'context' => 'field_heating_type:#allowed_values:Self-contained central heating',
    'location' => 'field:field_heating_type:#allowed_values:Self-contained central heating',
    'translation' => 'Etagenheizung',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['4283384a83b9fb13bde33d5fe2762200'] = array(
    'source' => 'First Occupancy after Renovation',
    'context' => 'field_status_quo:#allowed_values:First Occupancy after Renovation',
    'location' => 'field:field_status_quo:#allowed_values:First Occupancy after Renovation',
    'translation' => 'Erstbezug nach Renovierung',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['459dd9b9c6a6842b1fc82bc6ae795fe0'] = array(
    'source' => 'Modernised',
    'context' => 'field_status_quo:#allowed_values:Modernised',
    'location' => 'field:field_status_quo:#allowed_values:Modernised',
    'translation' => 'Modernisiert',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['5624214157087413fb26e34d98424f40'] = array(
    'source' => 'Description Commercial',
    'context' => 'field_object_desc_commercial:objekt:label',
    'location' => 'field:field_object_desc_commercial:objekt:label',
    'translation' => 'Beschreibung Gewerbe',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['57ebbcc2ba4f9f3bef0dd5772e65ae69'] = array(
    'source' => 'Description',
    'context' => 'description_field:category:label',
    'location' => 'field:description_field:category:label',
    'translation' => 'Beschreibung',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['6da9b7317c6c1286490e56b8bb1fb4c3'] = array(
    'source' => 'Category',
    'context' => 'field_kategorie:apartment:label',
    'location' => 'field:field_kategorie:apartment:label',
    'translation' => 'Kategorie',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['70568509a2a04b090a20beaceba0a2ce'] = array(
    'source' => 'Optional construction site',
    'context' => 'field_wug_opt_constrruct:objekt:label',
    'location' => 'field:field_wug_opt_constrruct:objekt:label',
    'translation' => 'Neubaureserve',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['9aca49c662bf4100cf04c28e526cb022'] = array(
    'source' => 'Completely Refurbished',
    'context' => 'field_status_quo:#allowed_values:Completely Refurbished',
    'location' => 'field:field_status_quo:#allowed_values:Completely Refurbished',
    'translation' => 'Totalsaniert',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['9e2d976649fd4f2ef5c32b30160e489a'] = array(
    'source' => 'Actual net rental income p.a.',
    'context' => 'field_wug_act_rent:residential_commercial_building:label',
    'location' => 'field:field_wug_act_rent:residential_commercial_building:label',
    'translation' => 'Nettokaltmieteinnahmen IST p.a.',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['a809bbfc627e995c623576da73ac3665'] = array(
    'source' => 'Total space',
    'context' => 'field_wug_total_space:objekt:label',
    'location' => 'field:field_wug_total_space:objekt:label',
    'translation' => 'Wohn-/Gewerbefläche',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['a9a1c488f4e5b75f249b78754542cbec'] = array(
    'source' => 'First Occupancy',
    'context' => 'field_status_quo:#allowed_values:First Occupancy',
    'location' => 'field:field_status_quo:#allowed_values:First Occupancy',
    'translation' => 'Erstbezug',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['abd8391e5cddff54bd9eef84b079edf2'] = array(
    'source' => 'Fittings',
    'context' => 'field_ausstattung:apartment:label',
    'location' => 'field:field_ausstattung:apartment:label',
    'translation' => 'Ausstattung',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['ae5a0a3692f79d9d0df4973ae503b359'] = array(
    'source' => 'Like New',
    'context' => 'field_status_quo:#allowed_values:Like New',
    'location' => 'field:field_status_quo:#allowed_values:Like New',
    'translation' => 'Wie neu',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['b19b809f9dcf47d12ff4a4461113081c'] = array(
    'source' => 'Central oil heating',
    'context' => 'field_heating_type:#allowed_values:Central oil heating',
    'location' => 'field:field_heating_type:#allowed_values:Central oil heating',
    'translation' => 'Öl-Zentralheizung',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['b6857a0d0bfdbde690d4a3371accf21a'] = array(
    'source' => 'Self-contained gas heating',
    'context' => 'field_heating_type:#allowed_values:Self-contained gas heating',
    'location' => 'field:field_heating_type:#allowed_values:Self-contained gas heating',
    'translation' => 'Gas-Etagenheizung',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['c72ab19662317758d7fcb89efd455da5'] = array(
    'source' => 'Description',
    'context' => 'description_field:status_quo:label',
    'location' => 'field:description_field:status_quo:label',
    'translation' => 'Beschreibung',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['ca67645d29ffbf74bc579f479e1cbe6b'] = array(
    'source' => 'Category',
    'context' => 'field_kategorie:objekt:label',
    'location' => 'field:field_kategorie:objekt:label',
    'translation' => 'Kategorie',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['d648c491fdca2ebe464d42d118bdfd2c'] = array(
    'source' => 'Actual net rental income p.a.',
    'context' => 'field_wug_act_rent:objekt:label',
    'location' => 'field:field_wug_act_rent:objekt:label',
    'translation' => 'Nettokaltmieteinnahmen IST p.a.',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['d9752693d425cf0310aecf4deebf3671'] = array(
    'source' => 'No Information',
    'context' => 'field_status_quo:#allowed_values:No Information',
    'location' => 'field:field_status_quo:#allowed_values:No Information',
    'translation' => 'Keine Angabe',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['dc5180abf1cbcc88897d2030b158b6f8'] = array(
    'source' => 'Location',
    'context' => 'field_object_location:objekt:label',
    'location' => 'field:field_object_location:objekt:label',
    'translation' => 'Lage',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['e0997f5f8ee7bab2863c7bc3818fb3c6'] = array(
    'source' => 'Partially restored',
    'context' => 'field_status_quo:#allowed_values:Partially restored',
    'location' => 'field:field_status_quo:#allowed_values:Partially restored',
    'translation' => 'Teilsaniert',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['e88abea36a37b5cb7e143afe35d30832'] = array(
    'source' => 'Description',
    'context' => 'description_field:vocabulary_6:label',
    'location' => 'field:description_field:vocabulary_6:label',
    'translation' => 'Beschreibung',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['eb3e2caf95a09abad4fadcaf46cfea98'] = array(
    'source' => 'Well preserved',
    'context' => 'field_status_quo:#allowed_values:Well preserved',
    'location' => 'field:field_status_quo:#allowed_values:Well preserved',
    'translation' => 'Gut erhalten',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['ef86fde8873fcafd226586456867c3bc'] = array(
    'source' => 'Well-Tended',
    'context' => 'field_status_quo:#allowed_values:Well-Tended',
    'location' => 'field:field_status_quo:#allowed_values:Well-Tended',
    'translation' => 'Gut erhalten',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['f2635d0186c7c57842627b32daf65aca'] = array(
    'source' => 'Description',
    'context' => 'description_field:vocabulary_5:label',
    'location' => 'field:description_field:vocabulary_5:label',
    'translation' => 'Beschreibung',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['f3102133723a75bc2f365add1109db7b'] = array(
    'source' => 'Other',
    'context' => 'field_object_other:objekt:label',
    'location' => 'field:field_object_other:objekt:label',
    'translation' => 'Sonstiges',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:field']['f6332aa8edb1a55b85c7b2e3272e5de0'] = array(
    'source' => 'Occupancy',
    'context' => 'field_wug_occupancy:objekt:label',
    'location' => 'field:field_wug_occupancy:objekt:label',
    'translation' => 'Vermietungsstand',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['06eae56a0c0f5714dbe6096e3d616c81'] = array(
    'source' => 'Terms of Service',
    'context' => 'item:28661:title',
    'location' => 'menu:item:28661:title',
    'translation' => 'AGB',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['0ade6a3b212df40aad56e4fd85b82d13'] = array(
    'source' => 'The <em>Main</em> menu is used on many sites to show the major sections of the site, often in a top navigation bar.',
    'context' => 'menu:main-menu:description',
    'location' => 'menu:menu:main-menu:description',
    'translation' => 'Das Menu oben neben dem Logo',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['160ba2b23baa516bbf86ee897ff42505'] = array(
    'source' => 'Privacy Policy',
    'context' => 'item:28660:title',
    'location' => 'menu:item:28660:title',
    'translation' => 'Datenschutz',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['296221cd1c090650ef95b75bdb768b4a'] = array(
    'source' => 'Buy',
    'context' => 'item:28651:title',
    'location' => 'menu:item:28651:title',
    'translation' => 'Kaufen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['340c5fd8cd16ff1373fa6c0a745f4877'] = array(
    'source' => 'Contact',
    'context' => 'item:28659:title',
    'location' => 'menu:item:28659:title',
    'translation' => 'Kontakt',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['360723af0622d9112e369a10896519d5'] = array(
    'source' => 'Offer',
    'context' => 'item:28653:title',
    'location' => 'menu:item:28653:title',
    'translation' => 'Anbieten',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['40eaa102d5bc704b058201f2458212fb'] = array(
    'source' => 'Favorites',
    'context' => 'item:28662:title',
    'location' => 'menu:item:28662:title',
    'translation' => 'Favoriten',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['4ac7d4baafdf61dd90dae9e02c9359e7'] = array(
    'source' => 'Search',
    'context' => 'item:28664:title',
    'location' => 'menu:item:28664:title',
    'translation' => 'Suchen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['5cf36afb9ce6ecdf2895b7b364262da2'] = array(
    'source' => 'Main menu',
    'context' => 'menu:main-menu:title',
    'location' => 'menu:menu:main-menu:title',
    'translation' => 'Hauptmenu',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['7d7484a92adb9578f94284a1041f35e1'] = array(
    'source' => 'About us',
    'context' => 'item:28654:title',
    'location' => 'menu:item:28654:title',
    'translation' => 'Über uns',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['987f439ea6355f00161f27cd440d2d87'] = array(
    'source' => 'Call us',
    'context' => 'item:28663:title',
    'location' => 'menu:item:28663:title',
    'translation' => 'Rufen Sie uns an',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['b334c11ab741d5dcd1ca3b7227786697'] = array(
    'source' => 'Team',
    'context' => 'item:28656:title',
    'location' => 'menu:item:28656:title',
    'translation' => 'Team',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['b354c2b8a75622c77128ed1b18001fcd'] = array(
    'source' => 'Imprint',
    'context' => 'item:28657:title',
    'location' => 'menu:item:28657:title',
    'translation' => 'Impressum',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['b7d28e1f716d623e8df76363470ea243'] = array(
    'source' => 'Footer Menu',
    'context' => 'menu:menu-footer-menu:title',
    'location' => 'menu:menu:menu-footer-menu:title',
    'translation' => 'Footer Menu',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['bf1f147084759c1f1ef7e500675c546d'] = array(
    'source' => 'Contact',
    'context' => 'item:28655:title',
    'location' => 'menu:item:28655:title',
    'translation' => 'Kontakt',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['d9a37835a759d58d1aceaaa41513720e'] = array(
    'source' => 'Rent',
    'context' => 'item:28652:title',
    'location' => 'menu:item:28652:title',
    'translation' => 'Mieten',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:menu']['ea7dab40d3b0a63f78b522ad199c00bf'] = array(
    'source' => 'Imprint',
    'context' => 'item:28658:title',
    'location' => 'menu:item:28658:title',
    'translation' => 'Impressum',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['02a26a78767e5b64ad8d6b48a828ebae'] = array(
    'source' => 'Hausgeld',
    'context' => 'expose:default:field:field_data_field_apart_hoa_fee:field_apart_hoa_fee:label',
    'location' => 'views:expose:default:field:field_data_field_apart_hoa_fee:field_apart_hoa_fee:label',
    'translation' => 'Hausgeld',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['03c4a6dd194880e02eb6cbf38de27c69'] = array(
    'source' => 'Wohnfläche',
    'context' => 'karten:kaufen:field:search_api_index_solr_node_index:field_apart_living_space:label',
    'location' => 'views:karten:kaufen:field:search_api_index_solr_node_index:field_apart_living_space:label',
    'translation' => 'Fläche',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['053c8e3461c8fe7bf401682400934392'] = array(
    'source' => 'Fläche',
    'context' => 'expose:default:field:field_data_field_apart_living_space:field_apart_living_space:label',
    'location' => 'views:expose:default:field:field_data_field_apart_living_space:field_apart_living_space:label',
    'translation' => 'Fläche',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['056992d726f762ce57665c8aa16984f8'] = array(
    'source' => 'Kategorie',
    'context' => 'admin_views_node:default:filter:field_data_field_kategorie:field_kategorie_tid:expose:label',
    'location' => 'views:admin_views_node:default:filter:field_data_field_kategorie:field_kategorie_tid:expose:label',
    'translation' => 'Kategorie',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['05706a4807672fbcdbeb2d4610fe05db'] = array(
    'source' => 'Living space',
    'context' => 'karten:default:filter:search_api_index_solr_node_index:field_apart_living_space:expose:label',
    'location' => 'views:karten:default:filter:search_api_index_solr_node_index:field_apart_living_space:expose:label',
    'translation' => 'Fläche',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['0d27782b39dfaf5bb905316a2d52ea4b'] = array(
    'source' => 'Beschädigte Behandlungsroutine field_data_taxonomy_vocabulary_8.taxonomy_vocabulary_8',
    'context' => 'wohnungsansicht:default:field:field_data_taxonomy_vocabulary_8:taxonomy_vocabulary_8:label',
    'location' => 'views:wohnungsansicht:default:field:field_data_taxonomy_vocabulary_8:taxonomy_vocabulary_8:label',
    'translation' => 'Kategorie',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['0d754c00ba18d79056013448a4fa3a0c'] = array(
    'source' => 'Etage',
    'context' => 'expose:default:field:field_data_field_apart_floor:field_apart_floor:label',
    'location' => 'views:expose:default:field:field_data_field_apart_floor:field_apart_floor:label',
    'translation' => 'Etage',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['0f1237b54d8ac411a5f4ecf212143ccd'] = array(
    'source' => 'Fittings',
    'context' => 'expose:default:field:field_data_field_ausstattung:field_ausstattung:label',
    'location' => 'views:expose:default:field:field_data_field_ausstattung:field_ausstattung:label',
    'translation' => 'Ausstattung',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['1586acd88fa0ff3d4ff57f5a07273d8b'] = array(
    'source' => 'Hausgeld',
    'context' => 'apartment:details:field:field_data_field_apart_hoa_fee:field_apart_hoa_fee:label',
    'location' => 'views:apartment:details:field:field_data_field_apart_hoa_fee:field_apart_hoa_fee:label',
    'translation' => 'Hausgeld',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['163ce32080c30729157a42b27951caf5'] = array(
    'source' => '« erste Seite',
    'context' => 'karten:kaufen:pager:tags:first',
    'location' => 'views:karten:kaufen:pager:tags:first',
    'translation' => '« erste',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['17d1fa957f0178d1f78a18ff39c9e86a'] = array(
    'source' => '<a href="/node/[field_obj_apartments-target_id]" title="Wohnung ansehen">[field_obj_apartments]</a> | <a href="/node/[field_obj_apartments-target_id]/edit?destination=admin/dash" title="Wohnung bearbeiten">bearbeiten</a> | <a href="/node/[field_obj_apartments-target_id]/translate?destination=admin/dash" title="Wohnung übersetzen">übersetzen</a>',
    'context' => 'admin:default:field:field_data_field_obj_apartments:field_obj_apartments:alter:text',
    'location' => 'views:admin:default:field:field_data_field_obj_apartments:field_obj_apartments:alter:text',
    'translation' => 'Bearbeiten',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['188341e23a8af21e00ca404b4745d3ec'] = array(
    'source' => 'Etage',
    'context' => 'apartment:details:field:field_data_field_apart_floor:field_apart_floor:label',
    'location' => 'views:apartment:details:field:field_data_field_apart_floor:field_apart_floor:label',
    'translation' => 'Etage',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['1eed7f750e9a85d19f96563f07d340d4'] = array(
    'source' => 'letzte Seite »',
    'context' => 'karten:mieten:pager:tags:last',
    'location' => 'views:karten:mieten:pager:tags:last',
    'translation' => 'letzte » ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['1f54df19c82d349d4333bac80b9e3ed4'] = array(
    'source' => 'Adresse',
    'context' => 'visitor_log_lite:default:field:ip_geoloc:formatted_address:label',
    'location' => 'views:visitor_log_lite:default:field:ip_geoloc:formatted_address:label',
    'translation' => 'Adresse',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['2011042077c3fcba981bcd8932221236'] = array(
    'source' => 'Bearbeiten',
    'context' => 'crm_core_contacts:default:field:views:nothing_1:alter:text',
    'location' => 'views:crm_core_contacts:default:field:views:nothing_1:alter:text',
    'translation' => 'Bearbeiten',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['20ae9c57087f02daadd046b6d007c633'] = array(
    'source' => 'Zimmer',
    'context' => 'karten:kaufen:field:search_api_index_solr_node_index:field_apart_rooms:label',
    'location' => 'views:karten:kaufen:field:search_api_index_solr_node_index:field_apart_rooms:label',
    'translation' => 'Zimmer',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['24ebacf7e0d8b915da7df0c372e70f19'] = array(
    'source' => 'Grundriß',
    'context' => 'expose:default:field:field_data_field_apart_floor_plan:field_apart_floor_plan:label',
    'location' => 'views:expose:default:field:field_data_field_apart_floor_plan:field_apart_floor_plan:label',
    'translation' => 'Grundriß',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['35c2253fc92b8b0990ab4595782f8bbf'] = array(
    'source' => 'Bearbeiten',
    'context' => 'crm_core_contact_to_user_management:default:field:views:nothing_1:alter:text',
    'location' => 'views:crm_core_contact_to_user_management:default:field:views:nothing_1:alter:text',
    'translation' => 'Bearbeiten',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['3ddb083c2c2285303879adbe9432cef5'] = array(
    'source' => 'Bezugsfrei ab',
    'context' => 'apartment:details:field:field_data_field_moving_in_from:field_moving_in_from:label',
    'location' => 'views:apartment:details:field:field_data_field_moving_in_from:field_moving_in_from:label',
    'translation' => 'Bezugsfrei ab',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['40160b57bcc1baaaeacc2aecd7664d5a'] = array(
    'source' => 'Zustand',
    'context' => 'expose:default:field:field_data_field_status_quo:field_status_quo:label',
    'location' => 'views:expose:default:field:field_data_field_status_quo:field_status_quo:label',
    'translation' => 'Zustand',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['41a4d7e84d05139b5f2c8e6b1c38690a'] = array(
    'source' => '‹ vorherige Seite',
    'context' => 'karten:mieten:pager:tags:previous',
    'location' => 'views:karten:mieten:pager:tags:previous',
    'translation' => '‹ zurück',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['41baed5b68601562068496c154db1585'] = array(
    'source' => 'Kategorie',
    'context' => 'admin:default:filter:field_data_field_kategorie:field_kategorie_tid:expose:label',
    'location' => 'views:admin:default:filter:field_data_field_kategorie:field_kategorie_tid:expose:label',
    'translation' => 'Kategorie',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['424c9fff9d065046cab524f824b5318b'] = array(
    'source' => 'Adresse',
    'context' => 'visitor_log:default:field:ip_geoloc:formatted_address:label',
    'location' => 'views:visitor_log:default:field:ip_geoloc:formatted_address:label',
    'translation' => 'Adresse',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['4321b2b22d908f44e908613fa3542d7a'] = array(
    'source' => 'Kaufpreis',
    'context' => 'karte:default:filter:field_data_field_apart_price:field_apart_price_value:expose:label',
    'location' => 'views:karte:default:filter:field_data_field_apart_price:field_apart_price_value:expose:label',
    'translation' => 'Kaufpreis',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['448d4786f2e772a1084926ab3765e553'] = array(
    'source' => 'Löschen',
    'context' => 'crm_core_contacts:default:field:views:nothing_2:alter:text',
    'location' => 'views:crm_core_contacts:default:field:views:nothing_2:alter:text',
    'translation' => 'Löschen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['4d8ff87be5631aab737ba2fdb855a3ca'] = array(
    'source' => 'Rooms',
    'context' => 'karten:kaufen:filter:search_api_index_solr_node_index:field_apart_rooms:expose:label',
    'location' => 'views:karten:kaufen:filter:search_api_index_solr_node_index:field_apart_rooms:expose:label',
    'translation' => 'Zimmer',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['4f1e35ea65e8650feaef21caf9f15e15'] = array(
    'source' => '« erste Seite',
    'context' => 'karten:mieten:pager:tags:first',
    'location' => 'views:karten:mieten:pager:tags:first',
    'translation' => '« erste',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['52697feb730a221b22dfe41df5c92193'] = array(
    'source' => 'Etagenzahl',
    'context' => 'apartment:details:field:field_data_field_no_of_floors:field_no_of_floors:label',
    'location' => 'views:apartment:details:field:field_data_field_no_of_floors:field_no_of_floors:label',
    'translation' => 'Etagenzahl',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['5861fee556d6f557fbf04e2dfb1f4c09'] = array(
    'source' => 'Search',
    'context' => 'karten:kaufen:exposed_form:submit_button',
    'location' => 'views:karten:kaufen:exposed_form:submit_button',
    'translation' => 'Suche',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['5e55ff4b9f66156d6056ac78ebd5361c'] = array(
    'source' => 'Etagenzahl',
    'context' => 'expose:default:field:field_data_field_no_of_floors:field_no_of_floors:label',
    'location' => 'views:expose:default:field:field_data_field_no_of_floors:field_no_of_floors:label',
    'translation' => 'Etagenzahl',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['608ec06150fc89da665e95eb2bcb8120'] = array(
    'source' => 'Bearbeiten',
    'context' => 'crm_activities_by_contact:default:field:views:nothing_2:alter:text',
    'location' => 'views:crm_activities_by_contact:default:field:views:nothing_2:alter:text',
    'translation' => 'Bearbeiten',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['609df30067dfd5d4fe6c0a0109815521'] = array(
    'source' => 'Kaufpreis',
    'context' => 'karten:kaufen:field:search_api_index_solr_node_index:field_apart_price:label',
    'location' => 'views:karten:kaufen:field:search_api_index_solr_node_index:field_apart_price:label',
    'translation' => 'Kaufpreis',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['61e1dcad573fc6ae4ad70693661527d2'] = array(
    'source' => 'Bearbeiten',
    'context' => 'webform_webforms:default:field:views_entity_node:edit_node:alter:text',
    'location' => 'views:webform_webforms:default:field:views_entity_node:edit_node:alter:text',
    'translation' => 'Bearbeiten',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['62b260bd4a5eab678f7574c5cdab3b74'] = array(
    'source' => 'Purchasing price',
    'context' => 'karten:default:filter:search_api_index_solr_node_index:field_apart_price:expose:label',
    'location' => 'views:karten:default:filter:search_api_index_solr_node_index:field_apart_price:expose:label',
    'translation' => 'Kaufpreis',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['671f3b20e05a581f9611ad1848eb3bcf'] = array(
    'source' => 'Living space',
    'context' => 'karten:kaufen:filter:search_api_index_solr_node_index:field_apart_living_space:expose:label',
    'location' => 'views:karten:kaufen:filter:search_api_index_solr_node_index:field_apart_living_space:expose:label',
    'translation' => 'Fläche',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['81a7db8af7a816fdaccbeecb285e7c0f'] = array(
    'source' => 'Living space',
    'context' => 'karten:mieten:filter:search_api_index_solr_node_index:field_apart_living_space:expose:label',
    'location' => 'views:karten:mieten:filter:search_api_index_solr_node_index:field_apart_living_space:expose:label',
    'translation' => 'Fläche',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['86e50da4103fdc8f6842daf1cadfb65d'] = array(
    'source' => 'Wohnungsnr.',
    'context' => 'admin_views_node:default:field:field_data_field_apart_no:field_apart_no:label',
    'location' => 'views:admin_views_node:default:field:field_data_field_apart_no:field_apart_no:label',
    'translation' => 'Wohnungsnummer',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['872b6275320ebdb8dbec8070c8e97249'] = array(
    'source' => 'Löschen',
    'context' => 'crm_activities_by_contact:default:field:views:nothing_3:alter:text',
    'location' => 'views:crm_activities_by_contact:default:field:views:nothing_3:alter:text',
    'translation' => 'Löschen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['8c4dae52e172b1c0af524e1e2079e94c'] = array(
    'source' => 'Zimmer',
    'context' => 'expose:default:field:field_data_field_apart_rooms:field_apart_rooms:label',
    'location' => 'views:expose:default:field:field_data_field_apart_rooms:field_apart_rooms:label',
    'translation' => 'Zimmer',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['8c9daed53b0feeb181399d610b349642'] = array(
    'source' => 'Provision',
    'context' => 'expose:default:field:field_data_field_apart_commission:field_apart_commission:label',
    'location' => 'views:expose:default:field:field_data_field_apart_commission:field_apart_commission:label',
    'translation' => 'Provision',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['8eb2d39a5e5a305e7222a05978f01f70'] = array(
    'source' => 'Beschreibung',
    'context' => 'wohnungsansicht:default:field:field_data_field_wohnungsbeschreibung:field_wohnungsbeschreibung:label',
    'location' => 'views:wohnungsansicht:default:field:field_data_field_wohnungsbeschreibung:field_wohnungsbeschreibung:label',
    'translation' => 'Beschreibung',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['904978bd4bfaa5c3aa47c92ac12c99a7'] = array(
    'source' => 'Provision',
    'context' => 'wohnungsansicht:default:field:field_data_field_sale_commission:field_sale_commission:label',
    'location' => 'views:wohnungsansicht:default:field:field_data_field_sale_commission:field_sale_commission:label',
    'translation' => 'Provision',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['91b32fbcbe4b8004bda3e9aa34fc2fce'] = array(
    'source' => 'letzte Seite »',
    'context' => 'karten:kaufen:pager:tags:last',
    'location' => 'views:karten:kaufen:pager:tags:last',
    'translation' => 'letzte » ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['96a63481b20fdb10413715c2123d4895'] = array(
    'source' => 'Delete',
    'context' => 'admin_views_user:default:action::views_bulk_operations_delete_item',
    'location' => 'views:admin_views_user:default:action::views_bulk_operations_delete_item',
    'translation' => 'Löschen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['98fed0ed7c424a7cdce46ab1762b0666'] = array(
    'source' => 'Zustand',
    'context' => 'apartment:details:field:field_data_field_status_quo:field_status_quo:label',
    'location' => 'views:apartment:details:field:field_data_field_status_quo:field_status_quo:label',
    'translation' => 'Zustand',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['a505e5a3cd6e7b39c030b7e02715fd09'] = array(
    'source' => 'Wohnfläche',
    'context' => 'karten:default:field:search_api_index_solr_node_index:field_apart_living_space:label',
    'location' => 'views:karten:default:field:search_api_index_solr_node_index:field_apart_living_space:label',
    'translation' => 'Fläche',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['a6cb3061032cb7cf4ab3b93422c381b4'] = array(
    'source' => 'letzte Seite »',
    'context' => 'backlinks:page:pager:tags:last',
    'location' => 'views:backlinks:page:pager:tags:last',
    'translation' => 'letzte » ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['a841f2b3119ca5a5ec2a2a76548ec236'] = array(
    'source' => 'Rent',
    'context' => 'karten:mieten:title',
    'location' => 'views:karten:mieten:title',
    'translation' => 'Mieten',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['a9992796ae6a90e9463f915011c65f89'] = array(
    'source' => 'Zustand',
    'context' => 'wohnungsansicht:default:field:field_data_field_status_quo:field_status_quo:label',
    'location' => 'views:wohnungsansicht:default:field:field_data_field_status_quo:field_status_quo:label',
    'translation' => 'Zustand',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['b612088b81b3753d25bcfdfe8fa10326'] = array(
    'source' => 'Adresse',
    'context' => 'order_locations:default:field:ip_geoloc:formatted_address:label',
    'location' => 'views:order_locations:default:field:ip_geoloc:formatted_address:label',
    'translation' => 'Adresse',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['b6681c7b2f0dadb54e5dc4cd660cf6c0'] = array(
    'source' => 'Rooms',
    'context' => 'karten:mieten:filter:search_api_index_solr_node_index:field_apart_rooms:expose:label',
    'location' => 'views:karten:mieten:filter:search_api_index_solr_node_index:field_apart_rooms:expose:label',
    'translation' => 'Zimmer',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['bb8a9112e6d9dd94b04124f4b0ef42e3'] = array(
    'source' => 'Heizung',
    'context' => 'apartment:details:field:field_data_field_heating_type:field_heating_type:label',
    'location' => 'views:apartment:details:field:field_data_field_heating_type:field_heating_type:label',
    'translation' => 'Heizung',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['c0e3866a37069f5cccee44dcb7e53c5e'] = array(
    'source' => 'Zimmer',
    'context' => 'karten:default:field:search_api_index_solr_node_index:field_apart_rooms:label',
    'location' => 'views:karten:default:field:search_api_index_solr_node_index:field_apart_rooms:label',
    'translation' => 'Zimmer',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['c17958eec6674bce77ffc569a0380631'] = array(
    'source' => 'Kaufpreis',
    'context' => 'expose:default:field:field_data_field_apart_price:field_apart_price:label',
    'location' => 'views:expose:default:field:field_data_field_apart_price:field_apart_price:label',
    'translation' => 'Kaufpreis',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['c63259125ead603b85bb738e1b20c737'] = array(
    'source' => 'Purchasing price',
    'context' => 'karten:kaufen:filter:search_api_index_solr_node_index:field_apart_price:expose:label',
    'location' => 'views:karten:kaufen:filter:search_api_index_solr_node_index:field_apart_price:expose:label',
    'translation' => 'Kaufpreis',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['c8a40da5f793b865335551b653d62b12'] = array(
    'source' => 'nächste Seite ›',
    'context' => 'karten:mieten:pager:tags:next',
    'location' => 'views:karten:mieten:pager:tags:next',
    'translation' => 'vor › ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['caf8b19a455e837abcff880c70ec2ccb'] = array(
    'source' => 'Delete',
    'context' => 'admin_views_file:default:action::views_bulk_operations_delete_item',
    'location' => 'views:admin_views_file:default:action::views_bulk_operations_delete_item',
    'translation' => 'Löschen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['d1e51b6b42854be02e4fb2b0a0917698'] = array(
    'source' => 'Rooms',
    'context' => 'karten:default:filter:search_api_index_solr_node_index:field_apart_rooms:expose:label',
    'location' => 'views:karten:default:filter:search_api_index_solr_node_index:field_apart_rooms:expose:label',
    'translation' => 'Zimmer',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['d6a1f72745f5ccc2fd22e58b0dfaa655'] = array(
    'source' => 'Purchasing price',
    'context' => 'karten:mieten:filter:search_api_index_solr_node_index:field_apart_price:expose:label',
    'location' => 'views:karten:mieten:filter:search_api_index_solr_node_index:field_apart_price:expose:label',
    'translation' => 'Kaufpreis',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['d6ffe407f44b46c87778fc8d947c95aa'] = array(
    'source' => 'Heizung',
    'context' => 'wohnungsansicht:default:field:field_data_field_heating_type:field_heating_type:label',
    'location' => 'views:wohnungsansicht:default:field:field_data_field_heating_type:field_heating_type:label',
    'translation' => 'Heizung',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['df964347d64fc9f4a2b951e2c897a1bd'] = array(
    'source' => 'nächste Seite ›',
    'context' => 'karten:kaufen:pager:tags:next',
    'location' => 'views:karten:kaufen:pager:tags:next',
    'translation' => 'vor › ',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['f09139755b9bf76bd015f53f266c1003'] = array(
    'source' => 'Buy',
    'context' => 'karten:kaufen:title',
    'location' => 'views:karten:kaufen:title',
    'translation' => 'Kaufen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['f381124b8d798d9ff2b6c81860193b7a'] = array(
    'source' => 'Schlafzimmer',
    'context' => 'apartment:details:field:field_data_field_apart_sleeping_rooms:field_apart_sleeping_rooms:label',
    'location' => 'views:apartment:details:field:field_data_field_apart_sleeping_rooms:field_apart_sleeping_rooms:label',
    'translation' => 'Schlafzimmer',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['f48627377f046c9e9cdb12eac6ef9c21'] = array(
    'source' => 'Schlafzimmer',
    'context' => 'expose:default:field:field_data_field_apart_sleeping_rooms:field_apart_sleeping_rooms:label',
    'location' => 'views:expose:default:field:field_data_field_apart_sleeping_rooms:field_apart_sleeping_rooms:label',
    'translation' => 'Schlafzimmer',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['f8329cce7ecc87a025036911ddc17c09'] = array(
    'source' => 'Provision',
    'context' => 'wohnungsansicht:default:field:field_data_field_rent_commission:field_rent_commission:label',
    'location' => 'views:wohnungsansicht:default:field:field_data_field_rent_commission:field_rent_commission:label',
    'translation' => 'Provision',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['f875fff0bd7d67dc2469b11e208e3587'] = array(
    'source' => 'Rooms',
    'context' => 'karten:mlt:field:search_api_index_solr_node_index:field_zimmer:label',
    'location' => 'views:karten:mlt:field:search_api_index_solr_node_index:field_zimmer:label',
    'translation' => 'Zimmer',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['f8ba9e5f8d885d52dad4aa03336e189e'] = array(
    'source' => 'Delete',
    'context' => 'admin_views_node:default:action::views_bulk_operations_delete_item',
    'location' => 'views:admin_views_node:default:action::views_bulk_operations_delete_item',
    'translation' => 'Löschen',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['f8dc7453611c890520d381066ad9462a'] = array(
    'source' => '‹ vorherige Seite',
    'context' => 'karten:kaufen:pager:tags:previous',
    'location' => 'views:karten:kaufen:pager:tags:previous',
    'translation' => '‹ zurück',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['fdfbbaf4c3b5d58a1c779bd55d84cf13'] = array(
    'source' => 'Badezimmer',
    'context' => 'apartment:details:field:field_data_field_apart_bathrooms:field_apart_bathrooms:label',
    'location' => 'views:apartment:details:field:field_data_field_apart_bathrooms:field_apart_bathrooms:label',
    'translation' => 'Badezimmer',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['de:views']['ffd3ac82fc9d01593387ede9989bdba5'] = array(
    'source' => 'Löschen',
    'context' => 'crm_core_contact_to_user_management:default:field:views:nothing_2:alter:text',
    'location' => 'views:crm_core_contact_to_user_management:default:field:views:nothing_2:alter:text',
    'translation' => 'Löschen',
    'plid' => 0,
    'plural' => 0,
  );
  return $translations;
}
